web:
  build: web
  ports:
    - "80"
  links:
    - rest
rest:
  build: java
  ports:
    - "8080:8080"
lb:
  image: eeacms/haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web
load_test:
  build: load_test
  links:
    - lb:web
integration_test:
  build: integration_test
  links:
    - web
