web:
  build: web
  ports:
    - "80"
  links:
    - rest
  volumes:
    - ./web/www:/var/www
rest:
  build: java
  ports:
    - "8080:8080"
lb:
  image: eeacms/haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web
